-- =====================================================================
--  PATCH 3 — invoices
--  Additive only. Adds an invoices table tied to schools, generated by
--  the operator from the console, viewable/downloadable by the school
--  itself via school_key + the contact_email already on file — no new
--  credential to manage.
-- =====================================================================

create table if not exists public.invoices (
  id             uuid primary key default gen_random_uuid(),
  invoice_number text unique not null,
  school_id      uuid not null references public.schools(id) on delete cascade,
  school_key     text not null,

  -- line items stored as JSON: [{ "description": "...", "qty": 1, "unit_price": 100000 }, ...]
  line_items     jsonb not null default '[]'::jsonb,
  currency       text not null default 'NGN',
  subtotal       numeric(14,2) not null default 0,
  total          numeric(14,2) not null default 0,

  notes          text,           -- payment instructions / terms shown on the invoice
  status         text not null default 'issued' check (status in ('issued','paid','cancelled')),

  issued_by      text not null,
  issued_at      timestamptz not null default now()
);

create index if not exists invoices_school_idx on public.invoices (school_id, issued_at desc);
create index if not exists invoices_number_idx on public.invoices (invoice_number);

alter table public.invoices enable row level security;

drop policy if exists invoices_operator_all on public.invoices;
create policy invoices_operator_all on public.invoices
  for all to authenticated using (public.is_operator()) with check (public.is_operator());

-- ---------------------------------------------------------------------
-- Human-friendly invoice numbers, e.g. INV-2026-0483
-- ---------------------------------------------------------------------
create or replace function public.gen_invoice_number()
returns text language plpgsql as $$
declare yr text := to_char(now(), 'YYYY'); n int;
begin
  n := floor(random() * 9000 + 1000)::int;
  return 'INV-' || yr || '-' || n::text;
end; $$;

-- ---------------------------------------------------------------------
-- Operator: create an invoice. Computes subtotal/total from line_items
-- server-side (never trust client arithmetic), logs to activity_log.
-- ---------------------------------------------------------------------
create or replace function public.create_invoice(
  p_school_id uuid, p_line_items jsonb, p_notes text, p_by text
) returns table (id uuid, invoice_number text, total numeric)
language plpgsql security definer set search_path = public as $$
declare
  v_key text;
  v_total numeric(14,2) := 0;
  v_number text;
  v_id uuid;
  item jsonb;
begin
  if not public.is_operator() then raise exception 'not authorised'; end if;

  select school_key into v_key from public.schools where id = p_school_id;
  if v_key is null then raise exception 'school not found'; end if;

  for item in select * from jsonb_array_elements(p_line_items) loop
    v_total := v_total + (coalesce((item->>'qty')::numeric, 1) * coalesce((item->>'unit_price')::numeric, 0));
  end loop;

  v_number := public.gen_invoice_number();

  insert into public.invoices (invoice_number, school_id, school_key, line_items, subtotal, total, notes, issued_by)
  values (v_number, p_school_id, v_key, p_line_items, v_total, v_total, p_notes, p_by)
  returning invoices.id into v_id;

  insert into public.activity_log (school_id, school_key, event, detail, amount, by_email)
  values (p_school_id, v_key, 'invoice_issued',
          'Invoice ' || v_number || ' issued', v_total, p_by);

  return query select v_id, v_number, v_total;
end; $$;

grant execute on function public.create_invoice(uuid, jsonb, text, text) to authenticated;

-- ---------------------------------------------------------------------
-- Public: list a school's invoices using school_key + the contact_email
-- already on file for that school. No separate credential required.
-- ---------------------------------------------------------------------
create or replace function public.list_school_invoices(p_school_key text, p_email text)
returns table (
  invoice_number text, line_items jsonb, currency text, subtotal numeric,
  total numeric, notes text, status text, issued_at timestamptz
) language sql stable security definer set search_path = public as $$
  select i.invoice_number, i.line_items, i.currency, i.subtotal, i.total, i.notes, i.status, i.issued_at
  from public.invoices i
  join public.schools s on s.id = i.school_id
  where s.school_key = lower(trim(p_school_key))
    and lower(coalesce(s.contact_email,'')) = lower(trim(p_email))
    and trim(p_email) <> ''
  order by i.issued_at desc;
$$;

grant execute on function public.list_school_invoices(text, text) to anon;

-- ---------------------------------------------------------------------
-- Public: fetch one invoice's full detail (incl. school name for the
-- PDF) by invoice number, still gated by school_key + email.
-- ---------------------------------------------------------------------
create or replace function public.get_school_invoice(p_school_key text, p_email text, p_invoice_number text)
returns table (
  invoice_number text, school_name text, line_items jsonb, currency text,
  subtotal numeric, total numeric, notes text, status text, issued_at timestamptz
) language sql stable security definer set search_path = public as $$
  select i.invoice_number, s.name, i.line_items, i.currency, i.subtotal, i.total, i.notes, i.status, i.issued_at
  from public.invoices i
  join public.schools s on s.id = i.school_id
  where s.school_key = lower(trim(p_school_key))
    and lower(coalesce(s.contact_email,'')) = lower(trim(p_email))
    and trim(p_email) <> ''
    and i.invoice_number = p_invoice_number;
$$;

grant execute on function public.get_school_invoice(text, text, text) to anon;

-- =====================================================================
--  Done.
-- =====================================================================
